[package]
name = "nucleus-recipes"
version = "0.1.0"
edition = "2021"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "Window", "Document", "Element", "HtmlElement", "Node", "Text", 
    "Storage", "WebSocket", "MessageEvent", "Location", "console"
] }
getrandom = { version = "0.2", features = ["js"] }
console_error_panic_hook = "0.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.7"
chrono = "0.4"
simd-json = "0.13"
mimalloc = "0.1"
nucleus-std = { path = "../../crates/nucleus-std" }
atom = { path = "../../crates/atom" }
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite"] }
tower-http = { version = "0.5", features = ["fs", "trace", "compression-full"] }

[lib]
crate-type = ["cdylib", "rlib"]
